# Generated by Django 6.0.2 on 2026-03-16 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_assessment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spring_user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('full_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dailyswot',
            name='created_at',
        ),
        migrations.AddField(
            model_name='dailyswot',
            name='error_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='RoadmapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('phase_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('depth', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='db.roadmap')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='UserKnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spring_user_id', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=100)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('mastery_scores', models.JSONField(default=dict)),
                ('critical_loopholes', models.JSONField(default=list)),
                ('top_error_type', models.CharField(max_length=50)),
                ('is_ready_for_roadmap', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('spring_user_id', 'domain')},
            },
        ),
        migrations.AddField(
            model_name='roadmap',
            name='knowledge_graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.userknowledgegraph'),
        ),
    ]
