# Generated by Django 6.0.2 on 2026-03-31 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_roadmap_alter_assessment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='knowledge_graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.userknowledgegraph'),
        ),
    ]
