# Generated by Django 6.0.2 on 2026-04-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_roadmap_knowledge_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='userknowledgegraph',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
