# Generated by Django 6.0.2 on 2026-04-19 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_userknowledgegraph_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='userknowledgegraph',
            name='title',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('ONBOARDING', 'Initial Diagnostic'), ('WEEKLY', 'Weekly Review'), ('REINFORCEMENT', 'Gap Filler')], default='ONBOARDING', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='tier',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userknowledgegraph',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userknowledgegraph',
            name='top_error_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AssessmentSWOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spring_user_id', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('error_analysis', models.JSONField(default=dict)),
                ('depth_score', models.IntegerField(default=5)),
                ('roadmap_directives', models.JSONField(default=dict)),
                ('suggested_focus', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swot', to='db.assessment')),
            ],
        ),
        migrations.DeleteModel(
            name='DailySWOT',
        ),
    ]
