# Generated by Django 6.0.2 on 2026-04-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_assessment_day_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userknowledgegraph',
            name='top_error_type',
        ),
        migrations.AddField(
            model_name='userknowledgegraph',
            name='has_roadmap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userknowledgegraph',
            name='test_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userknowledgegraph',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userknowledgegraph',
            name='spring_user_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
