from django.db import models
import uuid

# --- Choices ---

class AssessmentTier(models.TextChoices):
    EASY = 'EASY', 'Easy'
    MEDIUM = 'MEDIUM', 'Medium'
    HARD = 'HARD', 'Hard'

class AssessmentType(models.TextChoices):
    ONBOARDING = 'ONBOARDING', 'Initial Diagnostic'
    WEEKLY = 'WEEKLY', 'Weekly Review'
    REINFORCEMENT = 'REINFORCEMENT', 'Gap Filler'

# --- Models ---

class UserKnowledgeGraph(models.Model):
    """
    The Master Profile: Stores the current state of a user's brain for a domain.
    Updated after every assessment.
    """
    spring_user_id = models.CharField(max_length=255)
    domain = models.CharField(max_length=100)
    university = models.CharField(max_length=255, null=True, blank=True)
    
    # Progress Tracking
    is_onboarding_complete = models.BooleanField(default=False) 
    is_ready_for_roadmap = models.BooleanField(default=False)
    
    # Master Data
    mastery_scores = models.JSONField(default=dict)      # e.g., {"React": 85, "Hooks": 40}
    critical_loopholes = models.JSONField(default=list)  # List of topics needing urgent fix
    top_error_type = models.CharField(max_length=50, null=True, blank=True) # e.g., "Logic"
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('spring_user_id', 'domain'),)

class Assessment(models.Model):
    """
    Individual test sessions. Can be onboarding tiers or weekly tests.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    spring_user_id = models.CharField(max_length=255)
    domain = models.CharField(max_length=100)
    
    # New logic: Tier + Type
    tier = models.CharField(max_length=10, choices=AssessmentTier.choices, default=AssessmentTier.EASY)
    assessment_type = models.CharField(max_length=20, choices=AssessmentType.choices, default=AssessmentType.ONBOARDING)
    
    questions = models.JSONField()            # Generated by AI
    answers = models.JSONField(null=True, blank=True) # User responses
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

class AssessmentSWOT(models.Model):
    assessment = models.OneToOneField(Assessment, on_delete=models.CASCADE, related_name="swot")
    spring_user_id = models.CharField(max_length=255)
    
    score = models.FloatField()
    strengths = models.JSONField(default=list) 
    weaknesses = models.JSONField(default=list) 
    error_analysis = models.JSONField(default=dict) 
    depth_score = models.IntegerField(default=5)
    roadmap_directives = models.JSONField(default=dict)
    suggested_focus = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)# Details on Syntax vs Logic vs Conceptual

class Roadmap(models.Model):
    """
    The parent container for the learning plan.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    knowledge_graph = models.ForeignKey(UserKnowledgeGraph, on_delete=models.CASCADE, null=True, blank=True)
    spring_user_id = models.CharField(max_length=255)
    
    title = models.CharField(max_length=255)
    overview = models.TextField()
    full_data = models.JSONField()            # Full AI response for backup
    created_at = models.DateTimeField(auto_now_add=True)

class RoadmapTask(models.Model):
    """
    Individual steps/days in the roadmap.
    """
    roadmap = models.ForeignKey(Roadmap, related_name="tasks", on_delete=models.CASCADE)
    day_number = models.IntegerField()        # Sequence order
    phase_name = models.CharField(max_length=100)
    topic = models.CharField(max_length=255)
    task_description = models.TextField()
    depth = models.CharField(max_length=50)   # Beginner, Intermediate, Advanced
    
    is_completed = models.BooleanField(default=False)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['day_number']