spring.application.name=aitut
spring.main.allow-bean-definition-overriding=true
debug=true
# --- POSTGRESQL CONFIGURATION ---
spring.datasource.url=jdbc:postgresql://localhost:5432/Aitut
spring.datasource.username=postgres
spring.datasource.password=Nagraj@2005
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

## --- MAIL CONFIGURATION ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shieldx.app@gmail.com
spring.mail.password=ykjt qwsr inju lker
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
# Access token: 15 minutes | Refresh token: 30 days
app.jwtExpirationMs=900000
app.jwtRefreshExpirationMs=2592000000

spring.security.oauth2.client.registration.google.client-id=511625866788-i1cj7pgim65c9splvnd2chmptr1mrath.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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